# Generated by Django 4.1.7 on 2023-03-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_urls', models.TextField()),
                ('short_urls', models.CharField(max_length=20)),
            ],
        ),
    ]
